services:
  db:
    image: postgres:16-alpine
    container_name: gameshare_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/:/app/sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\" -d postgres" ]
      interval: 5s
      timeout: 3s
      retries: 20

  bot:
    build: .
    container_name: game_share_bot
    working_dir: /app
    volumes:
      - .:/app
      - site_packages:/usr/local/lib/python3.13/site-packages
      - usr_local_bin:/usr/local/bin
      - poetry_cache:/root/.cache/pypoetry
    env_file:
      - .env
    environment:
      CONN_STRING_SYNC: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      CONN_STRING_ASYNC: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: make start_bot


volumes:
  pgdata:
  site_packages:
  usr_local_bin:
  poetry_cache: